apiVersion: v1
kind: PersistentVolume
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: teleceptor-postgres
  name: teleceptor-postgres
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Mi
  storageClassName: manual
  hostPath:
    path: "/mnt/data"
