upstream django_app {
    server 127.0.0.1:8000;
}

server {
    listen 80;
    server_name localhost;

    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;
    client_max_body_size 50M;

    location / {
        proxy_pass http://unix:/run/gunicorn.sock;
    }

    location /static/ {
        root /home/teleceptor/teleceptor;
    }

}